[workspace]
members = ["crates/coordinator", "crates/integrity"]
resolver = "2"

[workspace.dependencies]
hdi = "0.3.2"
hdk = "0.2.2"
serde = "1"
holochain = "0.2.2"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
