[workspace]
members = ["crates/coordinator", "crates/integrity"]
resolver = "2"

[workspace.dependencies]
hdi = "0.2.0"
hdk = "0.1.0"
serde = "1"
holochain = "0.1.0"
fixt = "0.1.0"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
